### ISSUE TITLE
where is transfer_py3-py2.py 

### ISSUE THREAD

**Issue by soori95** [DirtyHarryLYL/DJ-RN#10]
Hello
In "Transfer the results to fit in Python 2.7" step: python script/transfer_py3-py2.py --res <Path to your SMPLify-X result>
I dont see any transfer_py3-py2.py in script folder. where is this file?

**Comment by Foruck** [comment]
Thanks for using! We have uploaded it in the latest commit.

**Comment by soori95** [comment]
thanks
