### ISSUE TITLE
$ python script/Download_data.py 1_aSwqUPCKHNSkx8WHIaHc3zjM0u50xPi Test_ambiguous.pkl

### ISSUE THREAD

**Issue by monacv** [DirtyHarryLYL/DJ-RN#12]
How do you run this? since I am getting error:

```
[26744:2271 0:466] 07:33:22 Wed Dec 23 [mona@goku:pts/5 +1] ~/research/code/DJ-RN
$ python script/Download_data.py 1_aSwqUPCKHNSkx8WHIaHc3zjM0u50xPi Test_ambiguous.pkl
script/Download_data.py:45: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if len(sys.argv) is not 3:
```

**Comment by DirtyHarryLYL** [comment]
Please follow the usage: 
https://github.com/DirtyHarryLYL/DJ-RN/blob/541dad0a2bd17ace87faadb3a31eb9c76c3e661b/script/Download_data.py#L46, e.g., python script/Download_data.py 1_aSwqUPCKHNSkx8WHIaHc3zjM0u50xPi  Data/Test_ambiguous.pkl

Or you could simply visit the google drive website and download the file via 
https://drive.google.com/file/d/ + 1_aSwqUPCKHNSkx8WHIaHc3zjM0u50xPi +/view?usp=sharing, i.e., 
https://drive.google.com/file/d/1_aSwqUPCKHNSkx8WHIaHc3zjM0u50xPi/view?usp=sharing
