### ISSUE TITLE
$ python script/filter_pose.py --ori openpose --fil filtered_results/ yields no result

### ISSUE THREAD

**Issue by monacv** [DirtyHarryLYL/DJ-RN#15]
After I run step 3, nothing happens. Could you please let me know what you expect to happen in the filtered_result folder that I have made?

```
416/31773MB
[94060:2271 0:603] 04:17:23 Thu Dec 24 [mona@goku:pts/9 +1] ~/research/code/DJ-RN
$ python script/filter_pose.py --ori openpose --fil filtered_results/
416/31773MB
[94060:2271 0:604] 04:17:28 Thu Dec 24 [mona@goku:pts/9 +1] ~/research/code/DJ-RN
$ ls filtered_results/
total 8.0K
drwxrwxr-x 14 mona mona 4.0K Dec 24 16:17 ..
drwxrwxr-x  2 mona mona 4.0K Dec 24 16:17 .
415/31773MB
[94060:2271 0:605] 04:17:33 Thu Dec 24 [mona@goku:pts/9 +1] ~/research/code/DJ-RN
$ ls openpose
total 3.2M
drwxrwsr-x  2 mona mona 624K Sep 16  2019 openpose_hico_test
drwxrwsr-x  2 mona mona 2.5M Nov  7  2019 openpose_hico_train
drwxrwxr-x  4 mona mona 4.0K Dec 24 14:39 .
drwxrwxr-x 14 mona mona 4.0K Dec 24 16:17 ..

```

**Comment by monacv** [comment]
@DirtyHarryLYL could you please tell what you expect to happen after running the following command? Thanks a bunch
`$ python script/filter_pose.py --ori openpose --fil filtered_results/`

**Comment by monacv** [comment]
@Foruck any lead on why 
`$ python script/filter_pose.py --ori openpose --fil filtered_results/`
yields no output and how that could be fixed? I am not getting any output and following the instruction in the README.md

**Comment by Foruck** [comment]
Sorry for the late reply!
In this case, you should run 
```shell
mkdir filtered_results
python script/filter_pose.py --ori openpose/openpose_hico_train --fil filtered_results/openpose_hico_train
python script/filter_pose.py --ori openpose/openpose_hico_test --fil filtered_results/openpose_hico_test
```

**Comment by monacv** [comment]
I already had the folder:

```
[95187:4668 0:1999] 05:22:07 Wed Jan 06 [mona@goku:pts/8 +1] ~/research/code/DJ-RN
$ mkdir filtered_results
mkdir: cannot create directory ‘filtered_results’: File exists
```

**Comment by monacv** [comment]
please note you have to lstrip('/') the image_name when you do os.path.join otherwise you will get errors in Ubuntu 20.04:

filtered_results/openpose_hico_train and os path join result:  /HICO_train2015_00028351_keypoints.json


![Screenshot from 2021-01-06 17-39-56](https://user-images.githubusercontent.com/76495162/103827098-34e09b80-5046-11eb-8a94-022abb368c82.png)


This is the change I made in dump line:
from:
        json.dump(f, open(os.path.join(args.fil, image_name + '_keypoints.json'), 'w'))

to:

        json.dump(f, open(os.path.join(args.fil, image_name.lstrip('/') + '_keypoints.json'), 'w'))
