### ISSUE TITLE
using -Result for folder name seems to cause some problems in Linux

### ISSUE THREAD

**Issue by monacv** [DirtyHarryLYL/DJ-RN#17]
while I can access the -Result folder from the GUI, I cannot $ cd into it. I suggest using a different name for the folder name.

```
[156225:2271 0:620] 05:05:43 Thu Dec 24 [mona@goku:pts/11 +1] ~/research/code/DJ-RN
$ cd -Results/
bash: cd: -R: invalid option
cd: usage: cd [-L|[-P [-e]] [-@]] [dir]
```
![Screenshot from 2020-12-24 17-06-35](https://user-images.githubusercontent.com/76495162/103107272-8e8aa400-460a-11eb-90b6-55e318b38795.png)

- in Linux commands is usually reserved for flags and args and that's why cd command is confused.

**Comment by DirtyHarryLYL** [comment]
Thanks, we will consider this for the next commit.
