### ISSUE TITLE
 In which file, is concatenated the word embedding and 18 point clouds of part set?

### ISSUE THREAD

**Issue by mohammad749** [DirtyHarryLYL/DJ-RN#18]
In the feature extraction step(Extract feature using PointNet), in which file, is concatenated the word embedding and 18 point clouds of part set?. That is part" 4.2. 3D Feature Extraction ( for the feature of part set, we concatenate it with PCA
reduced word embedding )"of your article?

**Comment by DirtyHarryLYL** [comment]
The corresponding scripts have been updated.
