### ISSUE TITLE
point_align_vis(result, obox, 'demo/object.obj', img)   File "/home/mona/research/code/DJ-RN/script/generate_utils.py", line 114, in point_align_vis     with open(mesh) as f: FileNotFoundError: [Errno 2] No such file or directory: 'demo/object.obj'

### ISSUE THREAD

**Issue by monacv** [DirtyHarryLYL/DJ-RN#19]
When I run the test.py that I have placed in script folder, I get the following error. Could you please share the object.obj?

```

[719535:3298 0:1345] 11:30:08 Wed Dec 30 [mona@goku:pts/17 +1] ~/research/code/DJ-RN/script
$ python test.py 
Traceback (most recent call last):
  File "test.py", line 43, in <module>
    point_align_vis(result, obox, 'demo/object.obj', img)
  File "/home/mona/research/code/DJ-RN/script/generate_utils.py", line 114, in point_align_vis
    with open(mesh) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'demo/object.obj'


```

In the demo folder, there is no object.obj file:

```
[719535:3298 0:1342] 11:29:22 Wed Dec 30 [mona@goku:pts/17 +1] ~/research/code/DJ-RN
$ ls script/demo/
total 1.8M
-rw-rw-r-- 1 mona mona 304K Dec 23 19:16 sample.jpg
-rw-rw-r-- 1 mona mona 1.2K Dec 23 19:16 result.pkl
-rw-rw-r-- 1 mona mona  188 Dec 23 19:16 obox.pkl
-rw-rw-r-- 1 mona mona 713K Dec 23 19:16 human.obj
-rw-rw-r-- 1 mona mona  188 Dec 23 19:16 hbox.pkl
drwxrwxr-x 2 mona mona 4.0K Dec 23 19:16 .
drwxrwxr-x 5 mona mona 4.0K Dec 30 23:27 ..
-rw-rw-r-- 1 mona mona 727K Dec 30 23:27 config.obj
```

Here's the test.py which is basically your jupyter notebook:

$ cat test.py 
```
import os
import os.path as osp
import numpy as np
import pickle
import trimesh
import torch
from generate_utils import get_order_obj, get_joints, get_param, point_align_vis, rotate, rotate_mul

class Arguments():
    def __init__(self, gender, smplx_path):
        self.gender     = gender
        self.smplx_path = smplx_path


args     = Arguments(gender='male', smplx_path='/home/mona/research/code/DJ-RN/models/smplx/')
obj_name = 'keyboard'
result   = pickle.load(open('demo/result.pkl', 'rb'))
hbox     = pickle.load(open('demo/hbox.pkl', 'rb'))
obox     = pickle.load(open('demo/obox.pkl', 'rb'))
mesh       = 'demo/human.obj'
img        = 'demo/sample.jpg'


list_hoi, order_obj_list, obj_para_dict = get_order_obj()
htri       = trimesh.load(mesh)
vertice    = np.array(htri.vertices,dtype=np.float32)
joints     = get_joints(args, torch.FloatTensor(torch.from_numpy(vertice.reshape(1,-1,3))))
shoulder_len = np.linalg.norm(joints[16] - joints[17])
radius    = obj_para_dict[obj_name]['ratio'] * shoulder_len
gamma_min = obj_para_dict[obj_name]['gamma_min']
gamma_max = obj_para_dict[obj_name]['gamma_max']
otri, _   = get_param(result, hbox, obox, htri, img, radius, gamma_min, gamma_max)
config    = htri + otri
ansp = rotate(joints - joints[0])
vertices = np.array(config.vertices)
vertices = vertices - joints[0]
vertices = rotate_mul(vertices, ansp)
config = trimesh.Trimesh(vertices=vertices, faces=config.faces)
_ = config.export('demo/config.obj')


point_align_vis(result, hbox, 'demo/human.obj', img)
point_align_vis(result, obox, 'demo/object.obj', img)


```

**Comment by Foruck** [comment]
Maybe try `demo/config.obj` instead of `demo/config.obj`?

**Comment by monacv** [comment]
@Foruck if you try config.obj instead of object.obj you get an error. I did try that initially.

**Comment by monacv** [comment]
this is what happens if you use config.obj instead of object.obj
![Screenshot from 2021-01-06 17-55-00](https://user-images.githubusercontent.com/76495162/103828113-665a6680-5048-11eb-85fe-052d9dd4d55c.png)

**Comment by Foruck** [comment]
Sorry for making a mistake! The `config.obj` is the generated 3D spatial configuration. We have fixed the bug in the latest version, where the `demo/object.obj` would be automatically after running the notebook step by step.

**Comment by yyvhang** [comment]
> When I run the test.py that I have placed in script folder, I get the following error. Could you please share the object.obj?
> 
> ```
> 
> [719535:3298 0:1345] 11:30:08 Wed Dec 30 [mona@goku:pts/17 +1] ~/research/code/DJ-RN/script
> $ python test.py 
> Traceback (most recent call last):
>   File "test.py", line 43, in <module>
>     point_align_vis(result, obox, 'demo/object.obj', img)
>   File "/home/mona/research/code/DJ-RN/script/generate_utils.py", line 114, in point_align_vis
>     with open(mesh) as f:
> FileNotFoundError: [Errno 2] No such file or directory: 'demo/object.obj'
> ```
> 
> In the demo folder, there is no object.obj file:
> 
> ```
> [719535:3298 0:1342] 11:29:22 Wed Dec 30 [mona@goku:pts/17 +1] ~/research/code/DJ-RN
> $ ls script/demo/
> total 1.8M
> -rw-rw-r-- 1 mona mona 304K Dec 23 19:16 sample.jpg
> -rw-rw-r-- 1 mona mona 1.2K Dec 23 19:16 result.pkl
> -rw-rw-r-- 1 mona mona  188 Dec 23 19:16 obox.pkl
> -rw-rw-r-- 1 mona mona 713K Dec 23 19:16 human.obj
> -rw-rw-r-- 1 mona mona  188 Dec 23 19:16 hbox.pkl
> drwxrwxr-x 2 mona mona 4.0K Dec 23 19:16 .
> drwxrwxr-x 5 mona mona 4.0K Dec 30 23:27 ..
> -rw-rw-r-- 1 mona mona 727K Dec 30 23:27 config.obj
> ```
> 
> Here's the test.py which is basically your jupyter notebook:
> 
> $ cat test.py
> 
> ```
> import os
> import os.path as osp
> import numpy as np
> import pickle
> import trimesh
> import torch
> from generate_utils import get_order_obj, get_joints, get_param, point_align_vis, rotate, rotate_mul
> 
> class Arguments():
>     def __init__(self, gender, smplx_path):
>         self.gender     = gender
>         self.smplx_path = smplx_path
> 
> 
> args     = Arguments(gender='male', smplx_path='/home/mona/research/code/DJ-RN/models/smplx/')
> obj_name = 'keyboard'
> result   = pickle.load(open('demo/result.pkl', 'rb'))
> hbox     = pickle.load(open('demo/hbox.pkl', 'rb'))
> obox     = pickle.load(open('demo/obox.pkl', 'rb'))
> mesh       = 'demo/human.obj'
> img        = 'demo/sample.jpg'
> 
> 
> list_hoi, order_obj_list, obj_para_dict = get_order_obj()
> htri       = trimesh.load(mesh)
> vertice    = np.array(htri.vertices,dtype=np.float32)
> joints     = get_joints(args, torch.FloatTensor(torch.from_numpy(vertice.reshape(1,-1,3))))
> shoulder_len = np.linalg.norm(joints[16] - joints[17])
> radius    = obj_para_dict[obj_name]['ratio'] * shoulder_len
> gamma_min = obj_para_dict[obj_name]['gamma_min']
> gamma_max = obj_para_dict[obj_name]['gamma_max']
> otri, _   = get_param(result, hbox, obox, htri, img, radius, gamma_min, gamma_max)
> config    = htri + otri
> ansp = rotate(joints - joints[0])
> vertices = np.array(config.vertices)
> vertices = vertices - joints[0]
> vertices = rotate_mul(vertices, ansp)
> config = trimesh.Trimesh(vertices=vertices, faces=config.faces)
> _ = config.export('demo/config.obj')
> 
> 
> point_align_vis(result, hbox, 'demo/human.obj', img)
> point_align_vis(result, obox, 'demo/object.obj', img)
> ```

Hi, when I run the demo.ipynb, to read the 'equation-root1.pkl', I got the error: () takes 1 positional argument but 2 were given. Did you meet that? If so, how did you solve it?
