### ISSUE TITLE
Data generation Run OpenPose for the images in the dataset.

### ISSUE THREAD

**Issue by GreenTeaHua** [DirtyHarryLYL/DJ-RN#2]
Data generation
Run OpenPose for the images in the dataset.
Alphapose ?

**Comment by DirtyHarryLYL** [comment]
Do you mean how to generate the pose estimation? In this work we need the human body, face and hand poses together for 3D recovering, thus we use openpose instead of alphapose.

**Comment by GreenTeaHua** [comment]
thank U for the comment.

**Comment by DirtyHarryLYL** [comment]
No problem~
