### ISSUE TITLE
How to run the demo code for my own images?

### ISSUE THREAD

**Issue by monacv** [DirtyHarryLYL/DJ-RN#20]
I am interested in running the Demo.ipynb for my own images. However, I am not sure where to create these .pkl files?
```

[812147:3298 0:1481] 04:37:55 Thu Dec 31 [mona@goku:pts/1 +1] ~/research/code/DJ-RN
$ fd hbox.pkl
script/demo/hbox.pkl
9201/31772MB
[812147:3298 0:1482] 04:38:01 Thu Dec 31 [mona@goku:pts/1 +1] ~/research/code/DJ-RN
$ rg hbox.pkl
script/test.py
18:hbox     = pickle.load(open('demo/hbox.pkl', 'rb'))

script/Demo.ipynb
59:    "hbox     = pickle.load(open('demo/hbox.pkl', 'rb'))\n",
```
and:

```

[812147:3298 0:1482] 04:38:01 Thu Dec 31 [mona@goku:pts/1 +1] ~/research/code/DJ-RN
$ rg hbox.pkl
script/test.py
18:hbox     = pickle.load(open('demo/hbox.pkl', 'rb'))

script/Demo.ipynb
59:    "hbox     = pickle.load(open('demo/hbox.pkl', 'rb'))\n",
9201/31772MB
[812147:3298 0:1483] 04:38:09 Thu Dec 31 [mona@goku:pts/1 +1] ~/research/code/DJ-RN
$ rg *pkl
script/Download_result.sh
7:python script/Download_data.py 10nUe9ruH7ZPTEh8WuV7lRCrRMCGFocKz ./-Results/400000_DJR_ambiguous.pkl.tar.gz
9:tar -xvzf 400000_DJR_ambiguous.pkl.tar.gz
10:rm -rf 400000_DJR_ambiguous.pkl.tar.gz

README.md
224:`python ./-Results/Evaluate_ambiguous.py ./-Results/400000_DJR_ambiguous.pkl DJR_ambiguous/`
9201/31772MB


```

How do you create them for custom images and not coco images? (imagine these custom images have COCO objects).

We have the following in one of the Demo.ipynb cells:
```

args     = Arguments(gender='male', smplx_path='/home/mona/research/code/DJ-RN/models/smplx/')
obj_name = 'keyboard'
result   = pickle.load(open('demo/result.pkl', 'rb'))
hbox     = pickle.load(open('demo/hbox.pkl', 'rb'))
obox     = pickle.load(open('demo/obox.pkl', 'rb'))
mesh       = 'demo/human.obj'
img        = 'demo/sample.jpg'
```

**Comment by DirtyHarryLYL** [comment]
For humans, we should prepare the human bounding boxes (hbox.pkl) and human 2D pose keypoints following our data format (or you can adjust the format yourself but ensure all the inputs are provided for Simplify-x). 
Openpose is recommended to support both body, hands, and face keypoints.

As for objects not in the range of coco 80, you could use other detectors that can afford the detection of your objects, or given just the objectness proposals from RPN. Similarly, you need to follow the input format or adjust the data loader.

**Comment by monacv** [comment]
@DirtyHarryLYL for COCO objects could you please share with me their object.obj files?

**Comment by Foruck** [comment]
Notice that we simplify the objects as a sphere, as in #19, the `object.obj` is automatically generated.
