### ISSUE TITLE
The size of features extracted 

### ISSUE THREAD

**Issue by mohammad749** [DirtyHarryLYL/DJ-RN#22]
In the "python Feature_extraction.py --input_list script/vertex_path_GT.txt --model_path ../Feature_extraction/model_10000.ckpt" step, what is the size of extracted feature?

**Comment by mohammad749** [comment]
The size of extracted features for me is (1, 1, 1228, 1, 256) that if we reshape it, it becomes a (1228,256). But in your paper, you told  input f3Dsp is [1228 * 384].

**Comment by Foruck** [comment]
Thanks for pointing out! It turns out that we miss some files to upload. We will upload the corresponding files asap.
