### ISSUE TITLE
Request for vertex_path_GT.txt file or the exact procedure for recreating it

### ISSUE THREAD

**Issue by monacv** [DirtyHarryLYL/DJ-RN#23]
I am running one of the steps in the README.md:

`python Feature_extraction.py --input_list script/vertex_path_GT.txt --model_path ../Feature_extraction/model_10000.ckpt`

and it requires a file that isn't in script folder.
Could you please share these files:
```
vertex_path_GT.txt
vertex_path_Neg.txt
vertex_path_Test.txt
```

**Comment by DirtyHarryLYL** [comment]
These files are generated by the previous operations as pointed in https://github.com/DirtyHarryLYL/DJ-RN/issues/21#issuecomment-757418296.
