### ISSUE TITLE
what is the expected result for this line of code `point_align_vis(result, obox, 'demo/object.obj', img)` in Demo.ipynb?

### ISSUE THREAD

**Issue by monacv** [DirtyHarryLYL/DJ-RN#24]
![Screenshot from 2021-01-06 17-56-49](https://user-images.githubusercontent.com/76495162/103828210-9144ba80-5048-11eb-96eb-b5210285793a.png)

After running this cell, a config.obj is dumped which I visualized it with meshlab. However, I am not sure where object.obj is supposed to come from or if it should be shared by you and what's the relation of it to config.obj to object.obj?
![Screenshot from 2021-01-06 17-56-08](https://user-images.githubusercontent.com/76495162/103829062-ccdf8480-5048-11eb-8816-649ab135d616.png)

**Comment by Foruck** [comment]
Same as #19 .
