### ISSUE TITLE
Example input/output for running step 4 and 5 of Data Generation

### ISSUE THREAD

**Issue by monacv** [DirtyHarryLYL/DJ-RN#25]
Could you please provide clear input and output examples for running step 4 and 5 of Data Generation in README.md?

For example, I am not sure what is exactly the "pose used for SMPLIify-X"?
`python script/assign_pose_GT.py --pose <path to your pose used for SMPLify-X> --res <path to your SMPLify-X result>`

![Screenshot from 2021-01-06 18-31-06](https://user-images.githubusercontent.com/76495162/103832927-92c4b180-504d-11eb-8402-b323f81675a7.png)

I am also not sure at all how to "Run SMPLify-X on the dataset with the filtered pose" as in step 4. Could you please provide step-to-step guide on how to do this?

Thanks a lot.

**Comment by Foruck** [comment]
You could get detailed information from https://github.com/vchoutas/smplify-x.
