### ISSUE TITLE
what is the number of Restore_flag?

### ISSUE THREAD

**Issue by mohammad749** [DirtyHarryLYL/DJ-RN#26]
I have two questions.
what is the number of Restore_flag?Based on the iCAN method, I put the number= 5.
when I run python tools/Test_HICO_DET_DJR.py --model <your model name> --iteration 400000 " I have following error
ValueError: Dimensions must be equal, but are 17 and 1228 for 'attention_3D/MatMul' (op: 'MatMul') with input shapes: [?,17], [1228,17].

**Comment by Foruck** [comment]
For Q1, we adopt the flag value as 5 from iCAN.
For Q2, we have fixed it in the latest version.
