### ISSUE TITLE
How to improve the iCAN performance? 

### ISSUE THREAD

**Issue by xxxzhi** [DirtyHarryLYL/DJ-RN#3]
Hi, in the readme file, you provide the iCAN result as follows,

> iCAN (BMVC2018)	19.61	17.29	20.30	22.10	20.46	22.59

However, in the paper, the result of iCAN is, 

> iCAN 14.84 10.45 17.03 13.42 17.18 12.17 17.46 15.65.

Would u mind provide the details of your new iCAN result?

**Comment by Foruck** [comment]
Sorry for the typo! 
By the way, the misleading result comes from our [PaStaNet](https://github.com/DirtyHarryLYL/HAKE-Action) on CVPR2020. 
Sorry again for the typo and thanks for pointing out!

**Comment by xxxzhi** [comment]
Thanks for your reply. Btw, I suppose you also have the result of HAKE-3D with PaStaNet.  Would mind provide the result?

**Comment by Foruck** [comment]
The combination of HAKE-3D and PaStaNet is still in progress.
