### ISSUE TITLE
correction in the file ult.py

### ISSUE THREAD

**Issue by mohammad749** [DirtyHarryLYL/DJ-RN#30]
Hello
You did not specify the second argument in line 261 of file ult.py(pc.append(pickle.load(open(config.cfg.SMPLX_PATH + '/object_GT/HICO_train2015_%08d/%03d_feature.pkl' % i, 'rb'))[None, ...])) . 
 I changed it to "pc.append(pickle.load(open(config.cfg.Spatial + '/object_GT/HICO_train2015_%08d/%03d_feature.pkl' % (image_id, i), 'rb'))[None, ...])"
I told you to correct it too

**Comment by mohammad749** [comment]
I think this line should be replaced with "pc.append(pickle.load(open(config.cfg.Spatial + '/object_GT/HICO_train2015_%08d/%03d_feature.pkl' % (image_id, GT[i][-1]), 'rb'))[None, ...])"

**Comment by Foruck** [comment]
Thanks for pointing out. We have fixed that. 
Since `GT[i][-1]` is the openpose index (also smplx obj index), and i is the pair index (also point cloud feature index), this line shouldn't be changed. We will figure out the reason asap.

**Comment by mohammad749** [comment]
Sorry,I don't understand
For some images, "i" may change from 1 to 7 or 8, but for images there is not 008_feature.pkl. for example there is 000_feature.pkl and  001_feature.pkl. Did you run it yourself?

**Comment by Foruck** [comment]
After another round of checking, I find that the real cause of these is in https://github.com/DirtyHarryLYL/DJ-RN/blob/fab6e1fd6cd4f98f2bb94f5ccf294ec3062de9f2/script/rotate_sampling_GT.py#L56-L64, while the `i` in L52,58,62 should be replaced by `item[6]`. We will 
Some of the codes were re-structured from a previous version that we used for our experiments reported, so there could be some consistency issues. Thanks a lot for your patience and your helpful issues! And we will keep on checking the code again to guarantee the availability and reproducibility.

**Comment by mohammad749** [comment]
In the file of generate_3D_obj_GT.py, the "i" in line 60 or Next lines should not be replaced by item[6]?

**Comment by Foruck** [comment]
Yes. Thanks for pointing out and I will fix that.

**Comment by mohammad749** [comment]
Can you please run it yourself from the beginning and correct it if there is a problem. Thanks

**Comment by Foruck** [comment]
We will run and revise the code from the beginning.

**Comment by mohammad749** [comment]
thanks a lot
