### ISSUE TITLE
features with size 1228*256

### ISSUE THREAD

**Issue by mohammad749** [DirtyHarryLYL/DJ-RN#32]
In step "python script/concat_w2v.py --SMPLX_PATH <path to your SMPL-X results> --GT ./Data/Trainval_GT_HICO_with_idx.pkl --Neg Trainval_Neg_HICO_with_idx.pkl --Test Test_Faster_RCNN_R-50-PFN_2x_HICO_DET_with_idx.pkl, the size of some features in negative samples does not change, ie they do not have a size of 1228 x 384 and they have a size of 1228 x 256, as in image \HICO_train2015_00000057

**Comment by Foruck** [comment]
Would you mind providing the feature filenames that the size did not changed?

**Comment by mahsa1363** [comment]
Due to the large volume of calculations, I used only 300 images of HICO-DET and they have this problem in features of negative sample in images of 25, 57 and 225.

**Comment by mohammad749** [comment]
Due to the large volume of computations, I used only 300 images of HICO-DET and they have this problem in features of negative sample in images of 25, 57 and 225.
