### ISSUE TITLE
How are the files part-w2v.pkl and obj-w2v.pk created

### ISSUE THREAD

**Issue by mahsa1363** [DirtyHarryLYL/DJ-RN#34]
Hello
How are the files part-w2v.pkl and obj-w2v.pk created and can you explain what they are? At this stage, different parts of the body are not identified? For example, what are the specifics of the fingers?

**Comment by DirtyHarryLYL** [comment]
These are word2vec files to import semantics into the representation.
For human body parts, we transform their names (10 parts like head, hands, feet, arms, legs, hip) into word embedding (300 sized). Similarly, for coco 80 objects' names, we also use 300-sized word embeddings to indicate them.

**Comment by mahsa1363** [comment]
Thanks
The file part-w2v.pkl is 55*128 and file obj-w2v.pk is 80*128, and neither is 300!! What do these sizes mean? How do we know which row in  part-w2v.pkl specifies the part of the hand fingers(for example)?

**Comment by Foruck** [comment]
1. Notice that we use PCA to reduce the dimension of w2v to 128 as stated in our paper.
2. The size means that the SMPL-X model is divided into 55 detailed parts according to [this file](https://owncloud.tuebingen.mpg.de/index.php/s/MWnr8Kso4K8T8at).
3. With the above file, you could visualize the correspondence between row-indexes and parts.

**Comment by mahsa1363** [comment]
Sorry I understand answer1 and 2 but did not understand answer 3. I mean, how do I know what these 55 part are and what each one is called? I mean, for example, how do I know what part of the body (hand,foot,leg,head,...) is belongs to the first row of these 55 rows and so on?
