### ISSUE TITLE
For obj_index=10 the scores matrix have no value

### ISSUE THREAD

**Issue by mary-arch** [DirtyHarryLYL/DJ-RN#36]
Hello
when I run "python ./-Results/Generate_detection.py --model /home/DJ-RN-master/-Results/400000_DJR"
I have this error:
Traceback (most recent call last):
  File "./-Results/Generate_detection.py", line 27, in <module>
    scores[obj_index] = np.concatenate(scores[obj_index], axis=0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate
For obj_index=10 the scores matrix have no value. What do I do?

**Comment by mary-arch** [comment]
Because I took a small amount of test data that does not have a value for some objects in scores. How can I correct the code?
I took 50 test data for exam

**Comment by Foruck** [comment]
Did you test your model on the full HICO-DET test set? If not, the number of pairs would not be matching and our NIS could not be successfully performed. Maybe you could skip the NIS procedure.
