### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (10701,) (1489274,) 

### ISSUE THREAD

**Issue by mary-arch** [DirtyHarryLYL/DJ-RN#38]
Hello
When I run "python ./-Results/Generate_detection.py --model <your test output directory, under ./-Results by default>" , I got bellow error:
Traceback (most recent call last):
  File "./-Results/Generate_detection.py", line 63, in <module>
    mask = inter_det_mask * nis_mask
ValueError: operands could not be broadcast together with shapes (10701,) (1489274,) 
It give the error in this line"mask = inter_det_mask * nis_mask"
why?

**Comment by Foruck** [comment]
Did you test your model on the full HICO-DET test set? If not, the number of pairs would not be matching and our NIS could not be successfully performed.

**Comment by mary-arch** [comment]
I used 100 test data because of I dont have space on my drive. What do I do to solve this problem with 100 test data?
 The pos and neg files is matched with the full of test data. What is pos and neg and how I can match it with the scores?

**Comment by Foruck** [comment]
1. Maybe you could try to extract the corresponding pos and neg value for the 100 test data from the file.
2. Please take reference from the [our previous work](https://github.com/DirtyHarryLYL/Transferable-Interactiveness-Network).
3. We are working on the journal version, where we will alleviate the storage space issue.
