### ISSUE TITLE
How can I get the GT and Neg data?

### ISSUE THREAD

**Issue by w1246410140** [DirtyHarryLYL/DJ-RN#41]
Would you like to explain about the GT and Neg data in step5 of Data generation. In the previous steps, I only get the dataset divided into train and test. Thank you very much!

**Comment by DirtyHarryLYL** [comment]
Here, GT and neg indicate the positive/interactive and negative/non-interactive human-object pairs. 
GT pairs are recorded in the HICO-DET labels. 
Negative pairs can be paired automatically, e.g., in an image, we can exhaustively pairing all detected humans and objects, then the pairs except for the GT pairs are the neg pairs.

**Comment by w1246410140** [comment]
Thanks for your reply!
So are GT and Neg samples used to learn interactiveness knowledge mentioned in your TIN paper? 
Is it right that the  GT and Neg samples are assigned automatically when I run the scripts in step5 of Data generation?

**Comment by DirtyHarryLYL** [comment]
Yes, GT and Neg pairs can be leveraged to learn the interactiveness and HOI classification. In the HOI classification, normally the pos:neg sample ratio is about 1:4.
The GT and Neg pairs with the corresponding human poses are preprepared in our file, so you could directly use them except that you want to reorganize the neg pairs for your convenience.

**Comment by w1246410140** [comment]
Thx！
