### ISSUE TITLE
The file generate_3D_obj_GT.py 

### ISSUE THREAD

**Issue by mahsa1363** [DirtyHarryLYL/DJ-RN#42]
Hello, it is possible to upload the correct files
I do not think file generate_3D_obj_GT.py is correct. When I run it, for example for image "HICO_train2015_00000001", there is a file 000.pkl in the results folder of --res, but when I run generate_3D_obj_GT.py, it has a value of -1 in the openpose index. Can you please look at it and rewrite it?

**Comment by DirtyHarryLYL** [comment]
Sometimes the openpose would not generate 2D pose, e.g., too small human box, severe occlusion, etc. Thus the subsequent 3D recover can just be a placeholder. If you process all images, we have provided the processing procedures to handle this issue.

**Comment by mahsa1363** [comment]
Thanks. problem solved. 
1-In line 60 of file generate_3D_obj_GT.py, you should rewrite "mesh       = os.path.join(args.res, 'meshes/HICO_train2015_%08d/%03d.obj' % (key, i))"" with "mesh       = os.path.join(args.res, 'meshes/HICO_train2015_%08d/%03d.obj' % (key, item[6]))"
2- Can you explain about file TrainvalNeg? What are the interactions in it and what is it in general?What is it used for?

**Comment by Foruck** [comment]
1. We have fixed the bug.
2. Please take reference from [this link](https://github.com/DirtyHarryLYL/Transferable-Interactiveness-Network/issues/57).
