### ISSUE TITLE
The 3D coordinates of the center of the sphere and the points of the human body are in the same coordinate?

### ISSUE THREAD

**Issue by masyrezaei** [DirtyHarryLYL/DJ-RN#43]
Thanks again,
The 3D coordinates of the center of the sphere and the points of the human body are in the same coordinate? I mean are they using the global coordinates? I want to use their relative distance from each other

**Comment by DirtyHarryLYL** [comment]
Yep, they are in one global coordinate system whose origin is the 3D human pelvis keypoint after a transformation.
