### ISSUE TITLE
which SMPLX should I download? Does it work also with 2020 version that has FLAME blendshapes?

### ISSUE THREAD

**Issue by monacv** [DirtyHarryLYL/DJ-RN#44]
Could you please comment if both versions are compatible with yours?

![Screenshot from 2021-05-20 19-43-17](https://user-images.githubusercontent.com/76495162/119062030-bdcbf400-b9a3-11eb-8391-025c247f7fb5.png)

**Comment by Foruck** [comment]
We used SMPL-X model for the current repo.
