### ISSUE TITLE
Questions I meet when making your model

### ISSUE THREAD

**Issue by Kimchuls** [DirtyHarryLYL/DJ-RN#6]
Thanks for sharing the great work. I really want to making your model but I meet some problems.
1. In step DATA GENERATION--Run SMPLify-X on the dataset with the filtered pose, I need to run SMPLify-X on the dataset but I cannot find the vposer_folder and smplx_parts_segm.pkl which you have mentioned it in another issue in the previous downloading files.
`python smplifyx/main.py --config cfg_files/fit_smplx.yaml 
    --data_folder ...
    --output_folder ...
    --visualize="True/False"
    --model_folder ...
    --vposer_ckpt VPOSER_FOLDER
    --part_segm_fn smplx_parts_segm.pkl`
2.In step 3D Human-Object Interaction Volume Generation and Visualization--Generation, I cannot run code in the DJ-RN/script/generate_utils.py, about line 260, if ansz>maxz. 
Traceback: `File ../sympy/core/relational.py, line 384, in __nonzero__, raise TypeError("cannot determine truth value of Relational")`
3.In step Extract feature using PointNet---Extract feature, I cannot find any folder or files named model_10000.ckpt ...?

**Comment by Foruck** [comment]
1. You could take reference from [this issue](https://github.com/vchoutas/smplify-x/issues/99) to download the files.
2. This could be a version issue. Which version of sympy are you using? The code mentioned is tested under Python 3.7 and sympy 1.4.
3. You could take reference from [here](https://github.com/DirtyHarryLYL/DJ-RN#extract-feature-using-pointnet), where we provide commands to download the pre-trained PointNet weight.

**Comment by Kimchuls** [comment]
The third question, I downloaded the weight according to the reference, and the command I use is `python Feature_extraction.py --input_list script/vertex_path_GT.txt --model_path root/model/DJ-RN/Feature_extraction/model_10000.ckpt`,but traceback tells me `tensorflow.python.framework.errors_impl.NotFoundError: root/model/DJ-RN/Feature_extraction; No such file or directory
`. The files I download are named model_10000.ckpt.data-00000-of-00001, model_10000.ckpt.index and model_10000.ckpt.meta. They are not same as `--model_path ../Feature_extraction/model_10000.ckpt` which is said in the README?

**Comment by Foruck** [comment]
`root/model/DJ-RN/Feature_extraction/model_10000.ckpt` seems to be the relative path, which is actually `($pwd)/root/model/DJ-RN/Feature_extraction/model_10000.ckpt`. You could try to use the absolute path. And it would help a lot if you could share the full directory structure.

**Comment by Kimchuls** [comment]
I put `model_10000.ckpt.data-00000-of-00001`, `model_10000.ckpt.index` and `model_10000.ckpt.meta` in the folder `/root/model/DJ-RN/Feature_extraction/model_10000.ckpt/`,or just in the folder `/root/model/DJ-RN/Feature_extraction/`, and both of them send me a same traceback `tensorflow.python.framework.errors_impl.NotFoundError: root/model/DJ-RN/Feature_extraction; No such file or directory`

**Comment by Foruck** [comment]
It seems like that a `/` was missed before `root/model/DJ-RN/Feature_extraction`, resulting in a NotFoundError.

**Comment by Kimchuls** [comment]
For Q2: I update my `python` to version 3.7.8 and my `sympy` version is 1.6.2, but for code `if (ansz > maxz): ansz = maxz` it still tracebacks `TypeError: cannot determine truth value of Relational`.....?
And I meet a new question that when running step`Experiments with our model-2: Train on HICO-DET`, DJ-RN/lib/network/DJR.py needs a file named `att_map.pkl`. Is this file comes from previous steps, or I need to download it from a website?

**Comment by Foruck** [comment]
For Q2, you could downgrade `sympy` to 1.4 (also downgrade `python` to 3.7.5 if necessary) and the issue would be fixed. 
For `att_map.pkl`, it should have already been downloaded if you had performed the full installation procedure.

**Comment by monacv** [comment]
@Kimchuls where did you find vertex_path_GT.txt? Could you please share it with me?
