### ISSUE TITLE
result of generate_3D_obj_GT.py look weird

### ISSUE THREAD

**Issue by monacv** [DirtyHarryLYL/DJ-RN#61]
Does this look what you have for ground truth or could you please share the ground truth for this image?
![Screenshot from 2021-06-03 20-30-25](https://user-images.githubusercontent.com/76495162/120728323-a6642f00-c4aa-11eb-9860-f7e02577826e.png)

the image is:
![HICO_train2015_00004909](https://user-images.githubusercontent.com/76495162/120728428-e5928000-c4aa-11eb-9e4d-f0d5a6bab213.jpg)

`HICO_train2015_00004909.jpg`

**Comment by DirtyHarryLYL** [comment]
GT here means using GT 2D h-o boxes, not the real 3D h-o. Because we can just use 2D clues to reconstruct the 3D h-o from the single RGB. Sometimes the reconstruction would not be accurate for hard cases.
