### ISSUE TITLE
  File "/scratch3/research/code/DJ-RN/script/generate_utils.py", line 131, in point_align_vis     point[1] *= -1 IndexError: invalid index to scalar variable. for Demo.ipynb 

### ISSUE THREAD

**Issue by monajalal** [DirtyHarryLYL/DJ-RN#68]
Could you please help me how to fix this error and why is it happening in your model?

```
point:  [-0.34036481  0.42585415 -0.14223516  1.        ]
point:  [0.05548287 0.66404343 0.28385553 1.        ]
point:  [0.13412607 0.18491974 0.09787998 1.        ]
point:  [-0.16665089  0.98304164  0.14549397  1.        ]
point:  [-0.20070657  0.99059296  0.25195605  1.        ]
point:  [-0.19348481  0.94724727  0.27389365  1.        ]
point:  [-0.15673089  0.97974503  0.13259335  1.        ]
point:  [-0.45096961  0.40110451  0.03551245  1.        ]
point:  [-0.20388865  0.94029754  0.23777734  1.        ]
point:  [-0.10884097  0.97093713  0.30640966  1.        ]
point:  [-0.56036353 -0.47730708 -0.30879885  1.        ]
point:  [-0.44436225 -0.39614624 -0.41218618  1.        ]
point:  [-0.16779009  0.84068835  0.21218522  1.        ]
point:  [-0.37815553  0.44930056 -0.05032021  1.        ]
point:  1.0
Traceback (most recent call last):
  File "djrn_demo.py", line 45, in <module>
    point_align_vis(result, obox, 'demo/object.obj', img)
  File "/scratch3/research/code/DJ-RN/script/generate_utils.py", line 131, in point_align_vis
    point[1] *= -1
IndexError: invalid index to scalar variable.

```

As you see above, point is always an array until once it is only one scalar value hence the IndexError is thrown.

The code is the same as `Demo.ipynb` but I just dumped it into a python file:

```
import os
import os.path as osp
import numpy as np
import pickle
import trimesh
import torch
from generate_utils import get_order_obj, get_joints, get_param, point_align_vis, rotate, rotate_mul

class Arguments():
    def __init__(self, gender, smplx_path):
        self.gender     = gender
        self.smplx_path = smplx_path



args     = Arguments(gender='male', smplx_path='/scratch3/research/data/smplify-x/models_smplx_v1_1/models/smplx/')
obj_name = 'keyboard'
result   = pickle.load(open('demo/result.pkl', 'rb'))
hbox     = pickle.load(open('demo/hbox.pkl', 'rb'))
obox     = pickle.load(open('demo/obox.pkl', 'rb'))
mesh       = 'demo/human.obj'
img        = 'demo/sample.jpg'


list_hoi, order_obj_list, obj_para_dict = get_order_obj()
htri       = trimesh.load(mesh)
vertice    = np.array(htri.vertices,dtype=np.float32)
joints     = get_joints(args, torch.FloatTensor(torch.from_numpy(vertice.reshape(1,-1,3))))
shoulder_len = np.linalg.norm(joints[16] - joints[17])
radius    = obj_para_dict[obj_name]['ratio'] * shoulder_len
gamma_min = obj_para_dict[obj_name]['gamma_min']
gamma_max = obj_para_dict[obj_name]['gamma_max']
otri, _   = get_param(result, hbox, obox, htri, img, radius, gamma_min, gamma_max)
config    = htri + otri
ansp = rotate(joints - joints[0])
vertices = np.array(config.vertices)
vertices = vertices - joints[0]
vertices = rotate_mul(vertices, ansp)
config = trimesh.Trimesh(vertices=vertices, faces=config.faces)
_ = otri.export('demo/object.obj')
_ = config.export('demo/config.obj')

point_align_vis(result, hbox, 'demo/human.obj', img)

point_align_vis(result, obox, 'demo/object.obj', img)





```

Could you please also show how the result of `point_align_vis(result, obox, 'demo/object.obj', img)` will look like?

**Comment by monajalal** [comment]
as for human mesh that is gonna be reprojected from 3D to 2D I have these

![Screenshot from 2021-06-29 17-30-30](https://user-images.githubusercontent.com/1892917/123870041-c8ad6900-d8ff-11eb-9247-8b682eedf9d8.png)

and I get this result:
![Screenshot from 2021-06-29 17-31-32](https://user-images.githubusercontent.com/1892917/123870104-de229300-d8ff-11eb-81e5-ca6b608986b1.png)

However, for the object, I don't even have any vertices, while I do have an object.obj dumped into demo folder:
![Screenshot from 2021-06-29 17-31-51](https://user-images.githubusercontent.com/1892917/123870188-fabecb00-d8ff-11eb-9dc1-bb4506651176.png)


![Screenshot from 2021-06-29 17-32-59](https://user-images.githubusercontent.com/1892917/123870253-13c77c00-d900-11eb-9b9d-f397afaf2f41.png)


Here is the object.obj opened in MeshLab. It has 162 vertices and 320 faces.
![Screenshot from 2021-06-29 17-35-58](https://user-images.githubusercontent.com/1892917/123870611-8e909700-d900-11eb-8e95-abde9732311c.png)


Here's the config.obj opened in MeshLab, it has 10,637 vertices and 21,228 faces.
![Screenshot from 2021-06-29 17-37-39](https://user-images.githubusercontent.com/1892917/123870747-c992ca80-d900-11eb-8489-dd9a305a7178.png)


Which also brings me to the question why we have fewer vertices in generate_utils for human?
`vert shape:  (10475, 3)`

**Comment by monajalal** [comment]
so I was able to fix this. 

problem is the 
at the beginning of .obj files.

I am not sure why the same line starting with # didn't produce any error for config.obj while the same line caused error for object.obj

```
mona@goku:~$ head config.obj 
# https://github.com/mikedh/trimesh
v 0.06554112 -0.35353449 -0.15660750
v 0.12260096 0.26944596 -0.09666567
v 0.11409152 0.25296563 -0.08211921
v 0.16982016 0.27564949 -0.01401609
v 0.10756608 0.26989394 0.07689193
v 0.10691840 0.23507541 0.08295418
v 0.18951936 -0.27950945 0.40542062
v -0.00643328 0.22738177 -0.06871684
v 0.15218432 0.13902885 -0.03334228
mona@goku:~$ head object.obj 
# https://github.com/mikedh/trimesh
v -0.26234362 0.06525587 0.58199048
v -0.26234362 0.41812477 0.58199048
v -0.06924281 0.30490637 0.47865486
v -0.06924281 0.17847426 0.47865486
v -0.44649713 0.24169031 0.38725544
v -0.35070959 0.17847492 0.65255725
v -0.35070959 0.30490571 0.65255725
v -0.32686317 0.04721821 0.47865486
v -0.32686317 0.43616241 0.47865486

```

This is related to this part of the code:

```
    with open(mesh) as f:
        while True:
            line = f.readline().split()
            if line[0] == 'v':
                vert.append(np.array([float(line[1]), float(line[2]), float(line[3])]))
            else:
                break
    vert = np.array(vert)
```
in `script/generate_utils.py`.

Here's the produced photo:
![Screenshot from 2021-06-29 17-48-38](https://user-images.githubusercontent.com/1892917/123872081-918c8700-d902-11eb-996d-3e91c777222a.png)

**Comment by yyvhang** [comment]
> as for human mesh that is gonna be reprojected from 3D to 2D I have these
> 
> ![Screenshot from 2021-06-29 17-30-30](https://user-images.githubusercontent.com/1892917/123870041-c8ad6900-d8ff-11eb-9247-8b682eedf9d8.png)
> 
> and I get this result: ![Screenshot from 2021-06-29 17-31-32](https://user-images.githubusercontent.com/1892917/123870104-de229300-d8ff-11eb-81e5-ca6b608986b1.png)
> 
> However, for the object, I don't even have any vertices, while I do have an object.obj dumped into demo folder: ![Screenshot from 2021-06-29 17-31-51](https://user-images.githubusercontent.com/1892917/123870188-fabecb00-d8ff-11eb-9dc1-bb4506651176.png)
> 
> ![Screenshot from 2021-06-29 17-32-59](https://user-images.githubusercontent.com/1892917/123870253-13c77c00-d900-11eb-9b9d-f397afaf2f41.png)
> 
> Here is the object.obj opened in MeshLab. It has 162 vertices and 320 faces. ![Screenshot from 2021-06-29 17-35-58](https://user-images.githubusercontent.com/1892917/123870611-8e909700-d900-11eb-8e95-abde9732311c.png)
> 
> Here's the config.obj opened in MeshLab, it has 10,637 vertices and 21,228 faces. ![Screenshot from 2021-06-29 17-37-39](https://user-images.githubusercontent.com/1892917/123870747-c992ca80-d900-11eb-8489-dd9a305a7178.png)
> 
> Which also brings me to the question why we have fewer vertices in generate_utils for human? `vert shape: (10475, 3)`

Hi, when I run the demo.ipynb, to read the 'equation-root1.pkl', I got the error: () takes 1 positional argument but 2 were given. Did you meet this bug? How did you solve it?
