### ISSUE TITLE
how to create the path including object_Neg for being able to run the concat_w2v.py script?

### ISSUE THREAD

**Issue by monajalal** [DirtyHarryLYL/DJ-RN#69]
So, when I search your repo for object_NEG I can only find two incidences one in a [utl ](https://github.com/DirtyHarryLYL/DJ-RN/blob/8451985364051c8e9acdc6bd9d9d6afda8188731/lib/ult/ult.py)file (that you haven't shown how to use it in README.md) and then another one in concat_w2v.py that I am intending to run.

![Screenshot from 2021-07-01 18-48-40](https://user-images.githubusercontent.com/1892917/124197727-2cb96400-da9d-11eb-8365-492e1fb10db1.png)

The problem is nowhere else before running the concat_w2v.py script you have instructed how to create the object_Neg folder as expected for concat_w2v.py same with the object_GT folder.

Could you kindly please provide instructions on how to create these folders and which exact files need to be moved over there?

Here's a code snippet of concat_w2v.py that requires stuff being loaded from the concat_w2v.py folder:

```
for key in Trainval_Neg:
    for i in range(len(Trainval_Neg[key])): 
        #pdb.set_trace()
        print(range(len(Trainval_Neg[key])))
        hoi_class = Trainval_Neg[key][i][1]#[0]
        print("I am here", i)
        cur_obj   = mapping[hoi_class]
        obj_holder = np.tile(obj_vec[int(cur_obj)], (312, 1))
        holder = np.concatenate([part_holder, obj_holder], axis=0)
        if not os.path.exists(args.SMPLX_PATH + '/object_NEG/HICO_train2015_%08d/%03d_feature.pkl' % (key, i)):
            print("path doesn't exists")
        if os.path.exists(args.SMPLX_PATH + '/results/HICO_train2015_%08d/%03d.pkl' % (key, Trainval_Neg[key][i][-1])):
            print("the path exists")
            pc = pickle.load(open(args.SMPLX_PATH + '/object_NEG/HICO_train2015_%08d/%03d_feature.pkl' % (key, i), 'rb'))
            pc = np.concatenate([pc, holder], axis=1)
            print('pc type: ', pc)
            print('pc shape: ', pc.shape)
            pickle.dump(pc, open(args.SMPLX_PATH + '/object_NEG/HICO_train2015_%08d/%03d_feature.pkl' % (key, i), 'wb'))

```

Here's another snipper in the same script that requires to load stuff from the non-existent object_GT folder:
```
for key in Trainval_GT:
    ## what's the class number for image #2.jpg?
    for i in range(len(Trainval_GT[key])):
        hoi_class = Trainval_GT[key][i][1][0]
        cur_obj   = mapping[hoi_class]
        #pdb.set_trace()
        obj_holder = np.tile(obj_vec[int(cur_obj)], (312, 1))
        holder = np.concatenate([part_holder, obj_holder], axis=0)
        if os.path.exists(args.SMPLX_PATH + '/results/HICO_train2015_%08d/%03d.pkl' % (key, Trainval_GT[key][i][-1])):
            pc = pickle.load(open(args.SMPLX_PATH + '/object_GT/HICO_train2015_%08d/%03d_feature.pkl' % (key, i), 'rb'))
            pc = np.concatenate([pc, holder], axis=1)
            pickle.dump(pc, open(args.SMPLX_PATH + '/object_GT/HICO_train2015_%08d/%03d_feature.pkl' % (key, i), 'wb'))
```

The same goes with the final part of the script that requires stuff to be loaded from the non-existent folder `object_test`:

```
for image_id in Test_RCNN:
    for i in range(len(Test_RCNN[image_id])):
        item = Test_RCNN[image_id][i]
        if item[1] == 'Human':
            for j in range(len(Test_RCNN[image_id])):
                if i == j:
                    continue
                Object = Test_RCNN[image_id][j]
                cur_obj = Object[4] - 1
                obj_holder = np.tile(obj_vec[cur_obj], (312, 1))
                holder = np.concatenate([part_holder, obj_holder], axis=0)
                if os.path.exists(args.SMPLX_PATH + '/results/HICO_test2015_%08d/%03d.pkl' % (image_id, item[-1])):
                    pc = pickle.load(open(args.SMPLX_PATH + '/object_test/HICO_test2015_%08d/human_%03d/%03d_feature.pkl' % (image_id, i, j), 'rb'))
                    pc = np.concatenate([pc, holder], axis=1)
                    pickle.dump(pc, open(args.SMPLX_PATH + '/object_test/HICO_test2015_%08d/human_%03d/%03d_feature.pkl' % (image_id, i, j), 'rb'))

```

While I can find codes in util.py for constructing `object_GT` and `object_Neg` folders, I am unsure how I could run the script for that purpose or at which step should I do so. Additionally, I don't see anything that creates `object_test` folder in your repo.

As for `object_test` I only see 3 folders that are loading it.
![Screenshot from 2021-07-01 18-56-58](https://user-images.githubusercontent.com/1892917/124198192-2d062f00-da9e-11eb-99a8-b575d323abc9.png)

Thanks a lot for your time @Foruck

**Comment by Foruck** [comment]
It is intended to be the directory you used for the corresponding '--save_obj_path' in step 6.
