### ISSUE TITLE
there is not merge_for_ambi.py

### ISSUE THREAD

**Issue by mahsa1363** [DirtyHarryLYL/DJ-RN#7]
hello
I want to implement your code.
I run "Generate_Ambiguous_HOI.sh". In last line there is "python script/merge_for_ambi.py" but there is not any file  "merge_for_ambi.py" in script folder.

**Comment by Foruck** [comment]
Thanks for using and sorry for the late reply! This is a file path issue and we have fixed it in the latest commit.

**Comment by mahsa1363** [comment]
thanks for your reply. in folder Data there is  merge_ambi.py but no
merge_for_ambi.py.
do you mean  merge_ambi.py  ?
Sorry, I had another question. I want to run your code on Windows with CPU.
Is it possible? If yes, how will the requirments_data.txt file change?

**Comment by Foruck** [comment]
A1: Yes.
A2:  We haven't tested our code on Windows with CPU yet, while we think the requirement doesn't need to change. Sorry for the limited help we could provide. Welcome to ask us if any issue appears.

**Comment by mahsa1363** [comment]
Hello
Excuse me, I'm a beginner. I wanted to connect with one of you who can help
me more. I want point clouds of humans and objects.Do you have these point
cloud files?
thanks

**Comment by Foruck** [comment]
The point cloud files of humans and objects could take approximately 1TB space, which we couldn't afford to share on cloud. Currently generating the files on a local server is still recommended.
We are working on the journal version of this project, and the storage issue would be addressed in the newer version, while more time is needed.

**Comment by mahsa1363** [comment]
So can you please guide me which part should be run to get these point
clouds ? I need to have the file of these point clouds. please help me.
thanks

**Comment by Foruck** [comment]
You could follow this two parts: [installation](https://github.com/DirtyHarryLYL/DJ-RN#installation) and [Data generation](https://github.com/DirtyHarryLYL/DJ-RN#data-generation) to get the point clouds. Follow all the steps included in this two part, and the point cloud files would be generated.

**Comment by mahsa1363** [comment]
Hello
Sorry to take your time, according to what you said, I run two parts of
Installation and Data generation. In the "Data generation" part and
in" Generate
3D spatial configuration." step, You take the "--smplx_path <path of the
smplx model>" as input but do not use smplx model in the"
generate_3D_obj_GT.py" file. You did not use the SMPLify model one at all.
How did you get the 3D model?
thanks and best regards

**Comment by Foruck** [comment]
The 3D model (`smplx model` mentioned above, could be downloaded following step 4 in [installation part](https://github.com/DirtyHarryLYL/DJ-RN#installation)) is used to get the 3D human joint locations. 
https://github.com/DirtyHarryLYL/DJ-RN/blob/41bd02146e38ee34ee5dbb58e0390581c8ac4bf4/script/generate_utils.py#L83
And they are also used by smplify-x to generate 3D human mesh in step 4 of [Data generation](https://github.com/DirtyHarryLYL/DJ-RN#data-generation).

**Comment by mahsa1363** [comment]
Yes . Now I understand. Only in step 4 there is no line of code. How to
get  3D human mesh in step 4 of Data generation
<https://github.com/DirtyHarryLYL/DJ-RN#data-generation> ؟ Does step 5 in
Data generation do all this?

**Comment by Foruck** [comment]
You could take reference from the official repo of [smplify-x](https://github.com/vchoutas/smplify-x) to see how to get 3D human mesh in step 4. And step 5 must be performed after step 1, 2, 3, 4.

**Comment by mahsa1363** [comment]
hello
thank you very much
If I have a question in the future, can I bother you?

**Comment by Foruck** [comment]
Welcome to bother if the question wasn't covered by our instructions or other issues from this repo and related repos.
