### ISSUE TITLE
Trainval_Neg.pkl file

### ISSUE THREAD

**Issue by mansooreh1** [DirtyHarryLYL/DJ-RN#71]
In Trainval_Neg.pkl ,Pair all the Human and Object that has the score higher than a threshold. HO pairs that are not included in the GT, are the negative examples.
If consider (IOU(human)and IOU(object))>threshold? Indeed close to each other or not?

**Comment by DirtyHarryLYL** [comment]
In Trainval_Neg.pkl ,Pair all the Human and Object that has the score higher than a threshold. HO pairs that are not included in the GT, are the negative examples.
--Yes. (score: IoU with GT box, detection confidence, all > thresholds)

If consider (IOU(human)and IOU(object))>threshold? Indeed close to each other or not?
--didn't get this point, in (IOU(human)and IOU(object)), what is "and"; "close to each other"?

**Comment by mansooreh1** [comment]
I mean the minimum of human overlap IoUh and object overlap IoUo exceeds threshold, i.e  min(IoUh; IoUo) >threshold. Is such a condition considered? I mean, is the human box considered close to the object box?

**Comment by DirtyHarryLYL** [comment]
H/O IoU box should all be > 0.5, yes, min() works.
No, no hand-crafted distance between human and object is explicitly defined as a constraint. But for many HOIs, h-o box distance is a useful clue.
