### ISSUE TITLE
What is shape and pose parameter?

### ISSUE THREAD

**Issue by mansooreh1** [DirtyHarryLYL/DJ-RN#72]
In your paper, you told
![image](https://user-images.githubusercontent.com/40629504/131544089-7efa462e-5ae4-47f1-ab69-e986bd38c2ea.png)
What is  ![image](https://user-images.githubusercontent.com/40629504/131544213-c7bb9cb0-a2ac-4acb-8f25-482b53f07076.png) and  ![image](https://user-images.githubusercontent.com/40629504/131544324-11b783d6-604d-4418-9c46-4d8089454bf9.png)
What do the pose and shape parameters mean?

**Comment by walnut-REE** [comment]
> In your paper, you told
> ![image](https://user-images.githubusercontent.com/40629504/131544089-7efa462e-5ae4-47f1-ab69-e986bd38c2ea.png)
> What is ![image](https://user-images.githubusercontent.com/40629504/131544213-c7bb9cb0-a2ac-4acb-8f25-482b53f07076.png) and ![image](https://user-images.githubusercontent.com/40629504/131544324-11b783d6-604d-4418-9c46-4d8089454bf9.png)
> What do the pose and shape parameters mean?

If I understand correctly it's described in the original SMPL paper?

**Comment by mansooreh1** [comment]
I'm a little confused. Can you explain? Is ![image](https://user-images.githubusercontent.com/40629504/131628082-536600fe-2c6c-47e5-9b96-8c7af002ca75.png) the point coordinates of joints in 2D and  ![image](https://user-images.githubusercontent.com/40629504/131628225-d844d90c-8075-4a6f-ac59-facda3ca53a0.png) the point coordinate of joints in 3D?

**Comment by DirtyHarryLYL** [comment]
2D keypoints are coordinates from Openpose.
The 3D pose is recorded as relative rotation angles from Smplify-x, which can be easily converted to XYZ.
Please refer to the [Smplify-x](https://github.com/vchoutas/smplify-x) for more.

**Comment by mansooreh1** [comment]
Thanks .I fully understood. Just what are  ![image](https://user-images.githubusercontent.com/40629504/131824590-444cfe5e-ff5d-4682-a676-20b2df2b93e6.png)?
In smplify-X told these two parameter are shape parameter(betas) and facial expression parameter(expression). Can you explain bit what that means?

**Comment by DirtyHarryLYL** [comment]
Compared to SMPlify, SMPLify-X not only encode the body shape but also the hand-face shape.
According to their setting, the 3D points on hand and face are also regressed, based on the Openpose 2D hand-face keypoints. Detailed illustration can be found in the Smplify-x output document.

**Comment by mansooreh1** [comment]
Thanks
