### ISSUE TITLE
plot visualized map of a output tensor of network

### ISSUE THREAD

**Issue by mansooreh1** [DirtyHarryLYL/DJ-RN#74]
Hello. If I want to plot visualized map of an output of a layer of network(for example if I want to plot visualized map of fc2_B in line 476 in DJR.py or fc2_G in line 478 in DJR.py ) which is a tensor  . how do this work?

**Comment by Foruck** [comment]
You could take reference from the code of [iCAN](https://github.com/vt-vl-lab/iCAN), where the attention maps are visualized, which is a good reference.
