### ISSUE TITLE
<lambda>() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by yyvhang** [DirtyHarryLYL/DJ-RN#78]
Hi, when I run the demo.ipynb, to read the 'equation-root1.pkl', I got the error: <lambda>() takes 1 positional argument but 2 were given. Could you please explain what's the data in ''equation-root1.pkl'', and how to solve this bug?

**Comment by Foruck** [comment]
Would you mind providing more running details like the version of python, also the detailed error info?

**Comment by yyvhang** [comment]
> Would you mind providing more running details like the version of python, also the detailed error info?

My Python version is 3.9, and I will get the following error:
TypeError: lambda () takes 1 positional argument but 2 were given.
I tried to debug and found this error is from the function "get param"--> line 174 from generate_utils.py. Besides, I have tried to use python 3.7 and python 2.7, but this error still exists.
Thanks for your reply！

**Comment by Foruck** [comment]
A possible reason might be the wrong version of sympy (1.4 in our project). If still not resolved, detailed traceback information would help.

**Comment by yyvhang** [comment]
> 

Thanks for your guidance, Sympy version 1.4 works in python3.9.
